table User {
  // Derived from Supabase
  user_id uuid  [pk]
  email varchar
}

table UserPartnerOwnership {
  user_id uuid
  partner_id int 
  approved boolean
  
  Indexes {
    (user_id, partner_id) [unique]
  }
}


Ref:  UserPartnerOwnership.user_id > User.user_id [delete:cascade]
Ref:  UserPartnerOwnership.partner_id > Partner.partner_id [delete:cascade]


table Partner {
  partner_id serial [pk]
  name varchar
  website varchar [null]
  telegram_handle varchar [null]
  twitter_id varchar [null]
  // Internal Flag here
  open_to_sponsor boolean
  stripe_account_id varchar
  // When a Partner wants to delete their acc - we indicate that it is inactive instead
  active bool
}

table Event {
  event_id serial [pk]
  user_id uuid 
  starts_at timestamptz
  ends_at timestamptz
  title varchar
  featured bool
  our_pick bool
  location_id serial 
  paid bool
  // In case we ever want to accept event $$
  stripe_event_id varchar
  remarks varchar 
  partnered bool
  event_series_id serial 
  partner_id serial [ref: > Partner.partner_id]
  scheduled_post timestamptz
  poster_link varchar
}

Ref: Event.location_id > Location.location_id
Ref: Event.event_series_id > EventSeries.event_series_id [delete:cascade]
Ref: Event.user_id > User.user_id

// Useful to help track recurring events - we specify end and start date
table EventSeries {
  event_series_id serial [pk] 
  recurring varchar // Support basic stuff like weekly, monthly,bi monthly
  //Thse can be null if recurring is set to null
  start_date timestamptz [null]
  end_date timestamptz  [null]
}

table Location {
  location_id serial [pk]
  address varchar 
  google_maps_link varchar
  city_id serial [ref: > City.city_id]
}

table City {
  city_id serial [pk]
  country_id serial [ref: > Country.country_id]
}

table Country {
  country_id serial [pk]
  country_name varchar 
}
   